using './main.bicep'

param location = 'australiaeast'
param staticWebAppLocation = 'eastasia'
param resourceGroupName = 'rg-wyuna-website-prod'
param staticWebAppName = 'swa-wyuna-website-prod'
param communicationServiceName = 'acs-wyuna-website-prod'
param emailServiceName = 'acs-email-wyuna-website-prod'
param emailDomainName = 'wyunacommunity.org'
param emailSenderUsername = 'contact.form'
param emailSenderDisplayName = 'Wyuna Community Inc'
